import { Sparkles, TrendingUp } from 'lucide-react';

export default function AiDiagnosticCard({ diagnostic }) {
  return (
    <div className="bg-white rounded-3xl p-6 shadow-sm border border-gray-100 h-full relative overflow-hidden">
      {/* Decorative background gradient matching your theme */}
      <div className="absolute top-0 right-0 w-32 h-32 bg-aura-purple/5 rounded-full blur-2xl -mr-10 -mt-10"></div>
      
      <div className="flex justify-between items-center mb-6 relative z-10">
        <div>
          <h3 className="font-semibold text-lg">{diagnostic.title}</h3>
          <p className="text-xs text-gray-500 mt-1">Generated by Aura AI</p>
        </div>
        <div className="bg-aura-purple/10 text-aura-purple p-2 rounded-full">
          <Sparkles size={18} />
        </div>
      </div>

      <div className="bg-gray-50 rounded-2xl p-5 border border-gray-100 relative z-10">
        <div className="flex items-center gap-2 mb-3">
          <span className="text-[10px] uppercase font-bold tracking-wider px-2 py-1 bg-emerald-100 text-emerald-700 rounded-md">
            {diagnostic.status}
          </span>
          <span className="flex items-center text-xs font-medium text-gray-500">
            <TrendingUp size={12} className="mr-1" /> {diagnostic.trend}
          </span>
        </div>
        <p className="text-sm text-gray-700 leading-relaxed font-medium">
          {diagnostic.message}
        </p>
      </div>

      <button className="w-full mt-6 bg-gradient-to-r from-aura-purple to-indigo-600 text-white py-3 rounded-xl font-medium text-sm hover:opacity-90 transition-opacity shadow-md">
        View Detailed Analysis
      </button>
    </div>
  );
}